package com.example.emma.qrcode_iteration2;

/**
 * Created by touchzy on 2018/4/15.
 */

public class DataArray {
    static public final int MAX = 1000000;
    static public float[][] Matrix = {
            {0,MAX,MAX,MAX,15,30,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,10,50,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX},
            {MAX,0,MAX,MAX,MAX,30,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX},
            {MAX,MAX,0,15,MAX,MAX,MAX,25,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,15,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX},
            {MAX,MAX,15,0,MAX,MAX,MAX,30,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,30,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX},
            {15,MAX,MAX,MAX,0,40,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,10,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX},
            {30,30,MAX,MAX,40,0,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,30,30,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX},
            {MAX,MAX,MAX,MAX,MAX,MAX,0,MAX,MAX,MAX,MAX,20,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,30,30,30,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX},
            {MAX,MAX,25,30,MAX,MAX,MAX,0,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,15,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,20,MAX,MAX,MAX},
            {MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,0,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,10,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX},
            {MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,0,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,30,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX},
            {MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,0,MAX,30,25,40,35,MAX,MAX,MAX,55,MAX,MAX,MAX,MAX,MAX,30,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX},
            {MAX,MAX,MAX,MAX,MAX,MAX,20,MAX,MAX,MAX,MAX,0,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,30,30,20,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX},
            {MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,30,MAX,0,35,MAX,10,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,30,MAX,35,MAX,MAX,MAX,MAX,MAX,20,MAX,MAX},
            {MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,25,MAX,35,0,20,30,MAX,MAX,MAX,35,MAX,MAX,MAX,MAX,MAX,50,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX},
            {MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,40,MAX,MAX,20,0,MAX,MAX,MAX,MAX,20,MAX,MAX,MAX,MAX,MAX,60,MAX,MAX,MAX,35,MAX,MAX,MAX,MAX,30,MAX},
            {MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,35,MAX,10,30,MAX,0,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,30,MAX,MAX,MAX,MAX,MAX,25,MAX,MAX},
            {MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,0,35,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,20,MAX,MAX,MAX,MAX,MAX,MAX,MAX},
            {MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,35,0,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,35,MAX,MAX,MAX,MAX,MAX,MAX,MAX},
            {MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,0,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,20,MAX,MAX,MAX,MAX,MAX},
            {MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,55,MAX,MAX,35,20,MAX,MAX,MAX,MAX,0,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,30,MAX,MAX,MAX,MAX,MAX,MAX},
            {MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,0,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,30,MAX,MAX,MAX,MAX,15},
            {10,MAX,MAX,MAX,10,30,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,0,MAX,55,MAX,MAX,MAX,MAX,MAX,MAX,MAX,50,MAX,MAX,MAX,MAX},
            {50,MAX,15,30,MAX,30,MAX,15,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,0,MAX,60,MAX,MAX,MAX,MAX,MAX,MAX,MAX,50,MAX,MAX,MAX},
            {MAX,MAX,MAX,MAX,MAX,MAX,30,MAX,MAX,MAX,MAX,30,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,55,MAX,0,MAX,MAX,30,MAX,MAX,MAX,MAX,20,MAX,MAX,MAX,MAX},
            {MAX,MAX,MAX,MAX,MAX,MAX,30,MAX,MAX,30,MAX,30,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,60,MAX,0,20,MAX,MAX,MAX,MAX,MAX,MAX,20,MAX,MAX,MAX},
            {MAX,MAX,MAX,MAX,MAX,MAX,30,MAX,MAX,MAX,30,20,30,50,60,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,20,0,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX},
            {MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,10,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,30,MAX,MAX,0,35,MAX,MAX,MAX,MAX,MAX,25,MAX,MAX},
            {MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,35,MAX,MAX,30,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,35,0,30,MAX,MAX,MAX,MAX,10,MAX,MAX},
            {MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,20,35,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,30,0,30,MAX,MAX,MAX,MAX,30,MAX},
            {MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,35,MAX,MAX,MAX,MAX,30,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,30,0,20,MAX,MAX,MAX,10,MAX},
            {MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,20,MAX,30,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,20,0,MAX,MAX,MAX,MAX,20},
            {MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,50,MAX,20,MAX,MAX,MAX,MAX,MAX,MAX,MAX,0,MAX,MAX,MAX,MAX},
            {MAX,MAX,MAX,MAX,MAX,MAX,MAX,20,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,50,MAX,20,MAX,MAX,MAX,MAX,MAX,MAX,MAX,0,MAX,MAX,MAX},
            {MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,20,MAX,MAX,25,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,25,10,MAX,MAX,MAX,MAX,MAX,0,MAX,MAX},
            {MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,30,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,30,10,MAX,MAX,MAX,MAX,0,MAX},
            {MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,15,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,MAX,20,MAX,MAX,MAX,MAX,0},
    };

    static public float[][] coord = {
            {290,250},
            {475,81},
            {740,180},
            {850,183},
            {190,287},
            {475,310},
            {455,600},
            {747,370},
            {143,737},
            {920,690},
            {735,861},
            {450,710},
            {563,945},
            {803,1000},
            {811,1100},
            {543,1000},
            {200,1215},
            {259,1450},
            {579,1550},
            {751,1230},
            {791,1480},
            {275,295},
            {675,290},
            {271,613},
            {659,689},
            {591,745},
            {219,773},
            {335,1000},
            {335,1180},
            {567,1200},
            {571,1380},
            {230,515},
            {640,520},
            {340,910},
            {560,1130},
            {750,1420}
    };



}

